-- AI GYM Workbook - Supabase migrations
--
-- 20260220000100_init
--
-- Core tables + triggers + RLS + policies.
--
-- Notes
-- - Keep this file focused on initial schema only (no seed data).
-- - Seed/demo data should live in supabase/seed.sql.
-- Create Exercises Table
create table if not exists public.exercises (
    id bigint generated by default as identity primary key,
    name text not null,
    category text check (category in ('cardio', 'gym')),
    tags text [],
    sets text,
    steps text [],
    image_url text,
    created_at timestamp with time zone default timezone('utc' :: text, now()) not null
);

-- Create Weekly Plan Table
create table if not exists public.weekly_plans (
    id uuid default gen_random_uuid() primary key,
    user_id uuid references auth.users(id),
    day_name text not null,
    exercise_id bigint references public.exercises(id) on delete cascade,
    created_at timestamp with time zone default timezone('utc' :: text, now()) not null,
    -- Ensure unique exercise per day for a user
    unique(user_id, day_name, exercise_id)
);

-- Create Users Profile Table
create table if not exists public.users (
    id uuid references auth.users(id) primary key,
    display_name text,
    avatar_url text,
    fitness_level text check (
        fitness_level in ('beginner', 'intermediate', 'advanced')
    ),
    goals text [],
    created_at timestamp with time zone default timezone('utc' :: text, now()) not null,
    updated_at timestamp with time zone default timezone('utc' :: text, now()) not null
);

-- v20240216_add_profile_fields: add richer profile attributes
alter table
    if exists public.users
add
    column if not exists gender text check (
        gender in (
            'male',
            'female',
            'non_binary',
            'prefer_not_to_say'
        )
    ),
add
    column if not exists age integer check (
        age between 10
        and 120
    ),
add
    column if not exists bio text;

-- Trigger to update updated_at
create
or replace function public.handle_updated_at() returns trigger as $ $ begin new.updated_at = timezone('utc', now());

return new;

end;

$ $ language plpgsql;

drop trigger if exists set_public_users_updated_at on public.users;

create trigger set_public_users_updated_at before
update
    on public.users for each row execute function public.handle_updated_at();

-- Enable Row Level Security
alter table
    public.exercises enable row level security;

alter table
    public.weekly_plans enable row level security;

alter table
    public.users enable row level security;

-- Policies for Exercises (Public Read)
drop policy if exists "Public exercises are viewable by everyone." on public.exercises;

create policy "Public exercises are viewable by everyone." on public.exercises for
select
    using (true);

-- Policies for Weekly Plans (Authenticated Users Only)
-- Allow users to manipulate their own rows
drop policy if exists "Users can view own plans." on public.weekly_plans;

create policy "Users can view own plans." on public.weekly_plans for
select
    using (auth.uid() = user_id);

drop policy if exists "Users can insert own plans." on public.weekly_plans;

create policy "Users can insert own plans." on public.weekly_plans for
insert
    with check (auth.uid() = user_id);

drop policy if exists "Users can update own plans." on public.weekly_plans;

create policy "Users can update own plans." on public.weekly_plans for
update
    using (auth.uid() = user_id);

drop policy if exists "Users can delete own plans." on public.weekly_plans;

create policy "Users can delete own plans." on public.weekly_plans for delete using (auth.uid() = user_id);

-- Policies for Users table
drop policy if exists "Users can view own profile." on public.users;

create policy "Users can view own profile." on public.users for
select
    using (auth.uid() = id);

drop policy if exists "Users can insert own profile." on public.users;

create policy "Users can insert own profile." on public.users for
insert
    with check (auth.uid() = id);

drop policy if exists "Users can update own profile." on public.users;

create policy "Users can update own profile." on public.users for
update
    using (auth.uid() = id);

drop policy if exists "Users can delete own profile." on public.users;

create policy "Users can delete own profile." on public.users for delete using (auth.uid() = id);